version: '2'
services:
  app:
    image: "financial-tracker:${APP_VERSION}"
    ports:
      - "9000:9000"
    environment:
      - FT_DB_HOST=db
      - FT_DB_PORT=5432
      - FT_DB_NAME=sample_db
      - FT_DB_USER=sample_db
      - FT_DB_PASSWORD=password
      - FT_SECRET="Super secret"
  proxy:
    image: "financial-tracker-proxy:${PROXY_VERSION}"
    ports:
      - "8000:80"
  db:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=sample_db
      - POSTGRES_PASSWORD=password